Dota_on_Rails/config/routes.rb
Rails.application.routes.draw do
  resources :matches, only: [:index, :show]

  match '/auth/:provider/callback', to: 'sessions#create', via: :all
  delete '/logout', to: 'sessions#destroy', as: :logout

  root to: 'matches#index'

end

Dota_on_Rails/app/models/match.rb
# == Schema Information
#
# Table name: matches
#
#  id          :integer          not null, primary key
#  uid         :integer          not null
#  user_id     :integer
#  winner      :string
#  first_blood :string
#  started_at  :datetime
#  mode        :string
#  duration    :string
#  cluster     :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  match_type  :string
#

require './lib/utils'

class Match < ActiveRecord::Base
  include Utils
  belongs_to :user
  has_many :players, dependent: :delete_all

  serialize :towers_status
  serialize :barracks_status

  def load_players!(radiant, dire)
    roster = {radiant: radiant, dire: dire}
    roster.each_pair do |k, v|
      v.players.each do |player|
        self.players.create({
                              uid: player.id,
                              items: parse_items(player.items),
                              hero: {id: player.hero.id,
                                     name: player.hero.name,
                                     image: player.hero.image_url(:sb)
                              },
                              ability_upgrades: player.ability_upgrades.map {
                                |ability_upgrade| {id: ability_upgrade.ability.id,
                                                   name: ability_upgrade.ability.name,
                                                   image: ability_upgrade.ability.image_url(:hp1),
                                                   level: ability_upgrade.level,
                                                   time: parse_duration(ability_upgrade.time)}
                              }.sort_by {|ability_upgrade| ability_upgrade[:level]},
                              additional_units: player.additional_units.map {
                                |unit| {name: unit.name,
                                        items: parse_items(unit.items)}
                              },
                              level: player.level,
                              kills: player.kills,
                              deaths: player.deaths,
                              assists: player.assists,
                              last_hits: player.last_hits,
                              denies: player.denies,
                              gold: player.gold,
                              gpm: player.gpm,
                              xpm: player.xpm,
                              status: player.status,
                              gold_spent: player.gold_spent,
                              hero_damage: player.hero_damage,
                              tower_damage: player.tower_damage,
                              hero_healing: player.hero_healing,
                              slot: player.slot,
                              radiant: k == :radiant
                            })
      end
    end
  end

  private

  def parse_items(items)
    items.delete_if {
      |item| item.name == "Empty"
    }.map  {
      |item| {id: item.id, name: item.name, image: item.image_url}
    }
  end
end

Dota_on_Rails/app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def show
    @match = Match.includes(:players).find_by(id: params[:id])
    @players = @match.players.order('slot ASC').group_by(&:radiant)
  end

  def index
    @matches = current_user.matches.order('started_at DESC') if current_user
  end
end

Dota_on_Rails/app/views/matches/_details_table.html.erb
<h3 class="<%= team %>">Team <%= team.titleize %></h3>

<table class="table table-hover table-striped info-table">
  <tr>
    <th>Player ID</th>
    <th>Hero</th>
    <th>Level</th>
    <th>Items</th>
    <th>Kills</th>
    <th>Deaths</th>
    <th>Assists</th>
    <th><abbr title="Last hits">LH</abbr></th>
    <th><abbr title="Denies">DN</abbr></th>
    <th>Gold (spent)</th>
    <th><abbr title="Gold per minute">GPM</abbr></th>
    <th><abbr title="Experience per minute">XPM</abbr></th>
    <th><abbr title="Hero damage">HD</abbr></th>
    <th><abbr title="Tower damage">TD</abbr></th>
    <th><abbr title="Hero healing">HH</abbr></th>
  </tr>
  <% players.each do |player| %>
    <tr>
      <td>
        <% if player.abandoned_or_not_connected? %>
          <abbr class="text-muted" title="<%= player.status.to_s.titleize %>"><%= player.uid %></abbr>
        <% else %>
          <%= player.uid %>
        <% end %>
      </td>
      <td><%= render 'player_hero', hero: player.hero %></td>
      <td><%= player.level %></td>
      <td><%= render 'items', items: player.items %></td>
      <td><%= player.kills %></td>
      <td><%= player.deaths %></td>
      <td><%= player.assists %></td>
      <td><%= player.last_hits %></td>
      <td><%= player.denies %></td>
      <td><%= player.gold %> (<%= player.gold_spent %>)</td>
      <td><%= player.gpm %></td>
      <td><%= player.xpm %></td>
      <td><%= player.hero_damage %></td>
      <td><%= player.tower_damage %></td>
      <td><%= player.hero_healing %></td>
    </tr>
    <% if player.additional_units.any? %>
      <% player.additional_units.each do |unit| %>
        <tr class="text-muted small">
          <td></td>
          <td><%= unit[:name] %></td>
          <td></td>
          <td><%= render 'items', items: unit[:items] %></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
</table>

<h4 class="<%= team %>">Builds</h4>

<table class="table table-hover table-striped info-table">
  <tr>
    <th>Hero</th>
    <% (1..25).each do |level| %>
      <th><%= level %></th>
    <% end %>
  </tr>
  <% @players[true].each do |player| %>
    <tr>
      <td><%= render 'player_hero', hero: player.hero %></td>
      <% player.ability_upgrades.each do |ability| %>
        <td class="text-center">
          <%= image_tag ability[:image], alt: ability[:name], title: ability[:name] %><br/>
          <small class="text-muted"><%= ability[:time] %></small>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

<h4 class="<%= team %>">Remaining buildings</h4>

<h5>Towers</h5>

<ul>
  <% @match.towers_status[team.to_sym].each do |b| %>
    <li><%= b.to_s.titleize %></li>
  <% end %>
</ul>

<h5>Barracks</h5>

<ul>
  <% @match.barracks_status[team.to_sym].each do |b| %>
    <li><%= b.to_s.titleize %></li>
  <% end %>
</ul>

Dota_on_Rails/app/views/matches/_items.html.erb
<% items.each do |item| %>
  <%= image_tag item[:image], alt: item[:name], title: item[:name] %>
<% end %>

Dota_on_Rails/app/views/matches/_player_hero.html.erb
<%= image_tag hero[:image], alt: hero[:name], title: hero[:name] %>

Dota_on_Rails/app/views/matches/index.html.erb
<% page_header 'Your matches' %>

<% if @matches && @matches.any? %>
  <table class="table table-striped table-hover info-table">
    <% @matches.each do |match| %>
      <tr>
        <td>
          <%= render 'player_hero', hero: current_user.played_for_in(match) %>
          <%= link_to match.started_at, match_path(match) %>
          <% if current_user.won?(match) %>
            <span class="label label-success">won</span>
          <% else %>
            <span class="label label-danger">lost</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

Dota_on_Rails/app/views/matches/show.html.erb
<% page_header "Match #{@match.uid} <small>#{@match.started_at}</small>" %>

<h2 class="<%= @match.winner.downcase %>"><%= @match.winner %> won</h2>

<p>
  <i class="glyphicon glyphicon-thumbs-up"></i> <%= @match.likes %>
  <i class="glyphicon glyphicon-thumbs-down"></i> <%= @match.dislikes %>
</p>

<ul>
  <li><strong>Mode:</strong> <%= @match.mode %></li>
  <li><strong>Type:</strong> <%= @match.match_type %></li>
  <li><strong>Duration:</strong> <%= @match.duration %></li>
  <li><strong>First blood:</strong> <%= @match.first_blood %></li>
</ul>

<%= render 'details_table', players: @players[true], team: 'radiant' %>

<%= render 'details_table', players: @players[false], team: 'dire' %>